account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="account/login.html", form_class=UserLoginForm
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/account/login/"),
        name="logout",
    ),
    path("register/", views.account_register, name="register"),
    path(
        "activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"
    ),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path(
        "wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"
    ),
]

basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.product_all, name="store_home"),
    path("detail/<slug:slug>", views.product_detail, name="product_detail"),
    path("phone/<slug:category_slug>/", views.category_list, name="category_list"),
    path("place/<slug:adressee_slug>/", views.adressee_list, name="adressee_list"),
    path("search/", views.Search.as_view(), name="search"),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class Adressee(MPTTModel):
    """
    Adressee Table implimented with MPTT.
    """

    name = models.CharField(
        verbose_name=_("Название адресата"),
        help_text=_("Необходимо и не должно повторяться"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(
        max_length=255, verbose_name=_("Adressee safe URL"), unique=True
    )
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Adressee")
        verbose_name_plural = _("Adressees")

    def get_absolute_url(self):
        return reverse("store:adressee_list", args=[self.slug])

    def __str__(self):
        return self.name


class Category(MPTTModel):
    """
    Category Table implimented with MPTT.
    """

    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(
        verbose_name=_("Category safe URL"), max_length=255, unique=True
    )
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(
        verbose_name=_("Product Name"),
        help_text=_("Required"),
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specifiction or features for the product types.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(
        verbose_name=_("Name"), help_text=_("Required"), max_length=255
    )

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    The Product table contining all product items.
    """

    adressee = models.ForeignKey(
        Adressee, on_delete=models.RESTRICT, null=True, blank=True
    )
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=_("title"),
        help_text=_("Required"),
        max_length=255,
    )
    description = models.TextField(
        verbose_name=_("description"), help_text=_("Not Required"), blank=True
    )
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=15,
        decimal_places=2,
    )
    discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=15,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    internalnumber = models.PositiveSmallIntegerField(
        blank=True, verbose_name="Внутренний номер"
    )
    inventorynumber = models.IntegerField(
        default=0, blank=True, verbose_name="Инвентарный №"
    )
    serialnumber = models.CharField(
        max_length=50, blank=True, default=0, verbose_name="Серийниый №"
    )
    rozport = models.PositiveSmallIntegerField(blank=True, verbose_name="Розетка(порт)")
    signature = models.BooleanField(default=False, verbose_name="Роспись")
    created_at = models.DateTimeField(
        _("Created at"), auto_now_add=True, editable=False
    )
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True
    )

    class Meta:
        ordering = ("created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_image"
    )
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

store/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView

from .models import Adressee, Category, Product


def product_all(request):
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)
    return render(request, "store/index.html", {"products": products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(
        category__in=Category.objects.get(name=category_slug).get_descendants(
            include_self=True
        )
    )
    return render(
        request, "store/category.html", {"category": category, "products": products}
    )


def adressee_list(request, adressee_slug=None):
    adressee = get_object_or_404(Adressee, slug=adressee_slug)
    products = Product.objects.filter(
        adressee__in=Adressee.objects.get(name=adressee_slug).get_descendants(
            include_self=True
        )
    )
    return render(
        request, "store/adressee.html", {"adressee": adressee, "products": products}
    )


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, is_active=True)
    return render(request, "store/single.html", {"product": product})


class Search(ListView):
    def get_queryset(self):
        return Product.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        return context

templates/store/adressee.html
{% extends "../base.html" %}
{% block title %}
{% if adressee %}{{ adressee.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ adressee.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div><b>Popular </b> products purchased</div>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'store:store_home' %}">Home</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>ФИО</th>
                <th>Аппарат</th>
                <th>Вн.номер</th>
                <th>Инв.номер</th>
                <th>Сер.номер</th>
                <th>Розетка и порт</th>
                <th>Стоимость</th>
                <th>Цена с НДС</th>
                <th>Адресат</th>
              </tr>
            </thead>
            {% for product in products %}
            <tbody>
              <tr>
                <th scope="row">{{ product.id }}</th>
                <td><a class="text-dark"
                  href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
                <td>{{ product.category }}</td>
                <td>{{ product.internalnumber }}</td>
                <td>{{ product.inventorynumber }}</td>
                <td>{{ product.serialnumber }}</td>
                <td>{{ product.rozport }}</td>
                <td>{{ product.discount_price }}</td>
                <td>{{ product.regular_price }}</td>
                <td>{{ product.adressee }}</td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/store/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div><b>Popular </b> products purchased</div>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'store:store_home' %}">Home</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>ФИО</th>
              <th>Аппарат</th>
              <th>Вн.номер</th>
              <th>Инв.номер</th>
              <th>Сер.номер</th>
              <th>Розетка и порт</th>
              <th>Стоимость</th>
              <th>Цена с НДС</th>
              <th>Адресат</th>
            </tr>
          </thead>
          {% for product in products %}
          <tbody>
            <tr>
              <th scope="row">{{ product.id }}</th>
              <td><a class="text-dark"
                href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
              <td>{{ product.category }}</td>
              <td>{{ product.internalnumber }}</td>
              <td>{{ product.inventorynumber }}</td>
              <td>{{ product.serialnumber }}</td>
              <td>{{ product.rozport }}</td>
              <td>{{ product.discount_price }}</td>
              <td>{{ product.regular_price }}</td>
              <td>{{ product.adressee }}</td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% block title %}Store - Low Prices in Books & more{% endblock %}
{% block content %}

<div class="container">
  <div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      
      <div class="album py-5">
        <div class="pb-3">
          <h1 class="h3">Список пользователей и телефонов</h1>
        </div>
        {% if not products %}
        <div class="col-12">There are currently no products active</div>
        {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-5">
          <table class="table">
            <thead>
              <tr>
                <th scope="row">#</th>
                <th>ФИО</th>
                <th>Аппарат</th>
                <th>Вн.номер</th>
                <th>Инв.номер</th>
                <th>Сер.номер</th>
                <th>Розетка и порт</th>
                <th>Стоимость</th>
                <th>Цена с НДС</th>
                <th>Адресат</th>
              </tr>
            </thead>
            {% for product in products %}
            <tbody>
              <tr>
                <th scope="row">{{ product.id }}</th>
                <td><a class="text-dark"
                  href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
                <td>{{ product.category }}</td>
                <td>{{ product.internalnumber }}</td>
                <td>{{ product.inventorynumber }}</td>
                <td>{{ product.serialnumber }}</td>
                <td>{{ product.rozport }}</td>
                <td>{{ product.discount_price }}</td>
                <td>{{ product.regular_price }}</td>
                <td>{{ product.adressee }}</td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
          
        </div>
        {% endif %}
      </div>
      
    </div>
  </div>

  {% endblock %}

templates/store/single.html
{% extends "../base.html" %}
{% load static %}
{% block stylesheet %}{% static 'store/css/store.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}

<div class="container">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
{% for message in messages  %}
  {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">временную корзину</a>.
{% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
      
      <div class="d-grid gap-2">
        <div class="d-flex d-flex-inline justify-content-between">
          <div><span class="h3">{{ product.regular_price }}</span>
            
          </div>
          <div>
            <label for="select">Qty</label>
            <select id="select" class="h6 store-select-dropdown">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
          </div>
        </div>
        <hr>
        
      </div>
    </div>
    <div class="col-md-7 col-lg-7 p-0">
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-12">
            <div class="card-body p-1">
              <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
              <p class="text-muted">Все данные пользователя</p>
              <hr>
              <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Добавить в корзину</button>
          <a href="{% url "account:user_wishlist" product.id  %}" class="btn btn-light fw500" role="button" aria-disabled="true">Добавить в временную корзину</a>



              <div class="bg-light">

                {% for image in product.product_image.all %}
                {% if image.is_feature %}
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ image.image.url }}"
                  alt="{{ image.image.alt_text }}">
                {% else %}
                <img class="img-fluid d-block-inline pt-3" width="100px" alt="Responsive image"
                  src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                {% endif %}
                {% endfor %}

              </div>
            </div>

            
            
            

          </div>
          
          

        </div>

        

      </div>
      
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>ФИО</th>
          <th>Аппарат</th>
          <th>Вн.номер</th>
          <th>Инв.номер</th>
          <th>Сер.номер</th>
          <th>Розетка и порт</th>
          <th>Стоимость</th>
          <th>Цена с НДС</th>
          <th>Адресат</th>
        </tr>
      </thead>
      {% for product in products %}
      <tbody>
        <tr>
          <th scope="row">{{ product.id }}</th>
          <td><a class="text-dark"
            href="#">{{ product.title }}</a></td>
          <td>{{ product.category }}</td>
          <td>{{ product.internalnumber }}</td>
          <td>{{ product.inventorynumber }}</td>
          <td>{{ product.serialnumber }}</td>
          <td>{{ product.rozport }}</td>
          <td>{{ product.discount_price }}</td>
          <td>{{ product.regular_price }}</td>
          <td>{{ product.adressee }}</td>
        </tr>
      </tbody>
      {% endfor %}
    </table>

  </div>

  <script>
    $(document).on('click', '#add-button', function (e) {
      e.preventDefault();
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_add" %}',
        data: {
          productid: $('#add-button').val(),
          productqty: $('#select option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          document.getElementById("basket-qty").innerHTML = json.qty
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  </script>

  {% endblock %}