basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.product_all, name="store_home"),
    path("detail/<slug:slug>", views.product_detail, name="product_detail"),
    path("phone/<slug:category_slug>/", views.category_list, name="category_list"),
    path("place/<slug:adressee_slug>/", views.adressee_list, name="adressee_list"),
    path("search/", views.Search.as_view(), name="search"),
]

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from store.models import Category, Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, "basket/summary.html", {"basket": basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        product_qty = int(request.POST.get("productqty"))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({"qty": basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({"qty": basketqty, "subtotal": baskettotal})
        return response


def basket_update():
    """ids = Basket(request)"""
    category = Category.objects.all()
    products = Product.objects.all()
    for product in products:
        product.category = category

    return Product.objects.bulk_update(products, update_fields=["category"])

templates/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Корзина</h1>
  </div>
  <div class="col-12">
    <table class="table">
      <tbody>
        <td>Управляйте <b> товарами </b></td>
        <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
        <td>Цена без НДС: {{basket.get_subtotal_price}}</td>
        <td></td>
              <td></td>

        <td>НДС: 12%</td>
        <td></td>
              <td></td>

        <td>Общая сумма: <b>{{basket.get_total_price}}</b></td>
      </tbody>
    </table>
    
  </div>
  <hr />
</div>
<div class="container">
  <div class="row g-3">
    {% if basket|length == 0 %}
    <div class="col-12">Твоя корзина пустая <a href="{% url 'store:store_home' %}">Склад</a></div>
    {% else %}
    <div class="col-12 bg-light p-3 d-flex justify-content-between">
      <div class="d-flex d-flex-inline">
        <div class="pe-3">
          <table class="table">
            <tbody>
              <td>Передача товара пользователю</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>
                <select id="select" style="width:150px;height:31px;">
                  {% for category in categories %}
                  <option value="{{category.id}}">{{category.name}}</option>
                  {% endfor %}
                </select>
              </td>
              <td><button class="btn btn-light" type="button">Сбросить</button></td>
              <td><a id="update-button" role="button" data-index="{{product.id}}" class="btn btn-success fw-bold" type="button">Передать</a></td>

            </tbody>
          </table>
          
          <div class="d-grid gap-2 ">
            
            
          </div>
        </div>
        <!--div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            Shipping options
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
              class="bi bi-chevron-down" viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
            </svg>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">Next day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul-->
        </div>
      </div>
      <div class="text-end">
        <!--div class=""> <span class="fw-bold"></span>
          <div id="subtotal" class="d-inline-flex fw-bold"></div>
        </div>
        <div id="">Плюс <span class="small">(НДС)</span>: <span class="fw-bold">12%</span></div>
        <div class="pt-2"> <span class="fw-bold h5"></span><span id="total"
            class="fw-bold h5">{{basket.get_total_price}}</span></div>
      </div-->
    </div>
    <div class="col-md-1 col-lg-1 order-md-last p-0 order-3">
      
    </div>
    <div class="col-md-11 col-lg-11 p-0">

      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">

              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>ФИО</th>
                    <th>Аппарат</th>
                    <th>Вн.номер</th>
                    <th>Инв.номер</th>
                    <th>Сер.номер</th>
                    <th>Розетка и порт</th>
                    <th>Стоимость</th>
                    <th>###</th>
                    <th>###</th>
                  </tr>
                </thead>
                {% for item in basket %}
                {% with product=item.product %}
                
                <tbody>
                  <tr>
                    <th scope="row">{{ product.id }}</th>
                    <td>
                      <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                      <p class="card-text pb-3">{{product.title}}</p></a>
                    </td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.internalnumber }}</td>
                    <td>{{ product.inventorynumber }}</td>
                    <td>{{ product.serialnumber }}</td>
                    <td>{{ product.rozport }}</td>
                    <td>{{ product.discount_price }}</td>
                   
                      <td><a type="button" id="" data-index="{{product.id}}"
                        class="update-button text-decoration-none small ps-3">Update</a>
                      </td>
                      <td><a type="button" id="delete-button" data-index="{{product.id}}"
                        class="delete-button text-decoration-none small">Delete</a></td>
                  </tr>
                </tbody>
                {% endwith %}
                
                {% endfor %}
              </table>
      </div>

    </div>
    {% endif %}
  </div>
</div>

<script>
  // Delete Item
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data("index"),

        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

        if (json.qty == 0) {
          total = 0
          subtotal = 0
        } else {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          subtotal = json.subtotal
        }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });

  // Update Item
  $(document).on("click", "#update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data("index"),
        categoryid: $('#select option:selected').val(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
    });
  });
</script>

{% endblock %}